---
############################
#  SHARED

tf-vars: &tf-vars
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((dev-cf-username))
  CF_PASSWORD: ((dev-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: dev
  AWS_ACCESS_KEY_ID: ((s3-tooling-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((s3-tooling-secret-access-key))
  TF_VAR_access_key: ((s3-tooling-access-key-id))
  TF_VAR_secret_key: ((s3-tooling-secret-access-key))
  TF_VAR_region: ((s3-tooling-region))

############################
#  JOBS

jobs:
  - name: terraform-plan-dev
    plan:
    - get: src
      resource: src
      trigger: true
      version: every
    - task: terraform-plan
      config:
        params:
          <<: *tf-vars
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hashicorp/terraform
            tag: 1.3.1
        inputs:
          - name: src
        run:
          dir: src
          path: terraform/dev
          args:
            - plan


############################
#  RESOURCES

resources:

  - name: src
    type: git
    icon: github
    source:
      uri: ((git-base-url))/cloud-gov/pages-infra
      branch: update-to-build-pages-dev

############################
#  RESOURCE TYPES

resource_types:

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

